spring:
  data:
    mongodb:
      database: oomall
      username: demouser
      password: '123456'
      authentication-database: oomall

replicaset:
  mongodb:
    replica-set: rs0
    read-preference: primary
    hosts: mongo1:27017,mongo2:27017,mongo3:27017